sentences = ['The quick brown fox jumps over the lazy dog near the quiet riverbank, startling the ducks into flight.',
             'She sells seashells by the seashore, but the shells she sells are surely seashells galore.',
             'In the midst of the bustling city, a small coffee shop offered a quiet retreat for weary travelers.',
             'The ancient castle stood tall on the hill, overlooking the vast, rolling landscape of green fields and forests.',
             'As the sun set behind the mountains,'
             ' the sky was painted in hues of orange, pink, and purple, creating a breathtaking view.',
             'The curious cat tiptoed through the garden,'
             ' carefully avoiding the blooming flowers and buzzing bees.',
             'On a dark and stormy night, the old lighthouse keeper braved the elements to ensure the beacon stayed lit.',
             'The elegant ballerina gracefully twirled across the stage, her movements synchronized with the soft melody of the piano.', 'The mysterious stranger left a cryptic note on the doorstep, sparking a series of unexpected events in the quiet village.',
             'The young artist spent hours in her studio, painting vibrant landscapes inspired by her travels around the world.',
             'In the heart of the forest, a hidden waterfall cascaded into a crystal-clear pool, surrounded by lush greenery.',
             'The old library was filled with dusty books, each one containing stories of adventure, romance, and mystery.',
             'The clever detective pieced together the clues, '
             'unraveling the mystery behind the series of strange occurrences in the town.',
             'As the orchestra played, the conductor led with passion, bringing the symphony to life in the grand concert hall.',
             'The adventurer set out on a quest to find the lost treasure, guided only by an ancient map and a sense of determination.',
             'The garden was a riot of colors, with flowers of every hue blooming in the warm summer sunshine.',
             'The small town came together to celebrate the annual festival, with music, dancing, and delicious food.',
             'The scientist worked tirelessly in the lab, experimenting with new compounds in hopes of discovering a groundbreaking cure.',
             'The majestic eagle soared high above the mountains, its sharp eyes scanning the landscape below for prey.',
             'The bustling marketplace was filled with the sounds of merchants shouting, customers haggling, and children laughing.',
             'The old oak tree in the park had stood for centuries, its branches providing shade and shelter to countless generations.',
             'The playwright crafted a compelling story that explored themes of love, loss, and redemption.',
             'The chef prepared a sumptuous feast, using fresh ingredients and secret recipes passed down through generations.',
             'The novelist sat at her desk, typing furiously as she brought her characters and their world to life on the page.',
             'The astronomer gazed through the telescope, marveling at the beauty and complexity of the distant galaxies.',
             'The marathon runner pushed through the pain and exhaustion, determined to reach the finish line.',
             "The pianist's fingers danced across the keys, filling the room with a beautiful and haunting melody.",
             'The explorer ventured deep into the jungle, encountering exotic animals and plants along the way.',
             "The philosopher pondered the mysteries of existence, seeking answers to life's most profound questions.",
             'The architect designed a stunning building, blending modern aesthetics with functional elegance.']